name: Example Workflow
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"

  build:
    runs-on: ubuntu-latest
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest
      
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: |
            **/pytest.xml
